spring.application.name=inlax-auth

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/inlax_auth
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect